/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entity_common_pb = require('../entity/common_pb.js');
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.Delivery', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.Delivery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.Delivery';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Delivery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.toObject = function(includeInstance, msg) {
  var f, obj = {
    deliveryAddressRaw: jspb.Message.getFieldWithDefault(msg, 10, ""),
    deliveryAddress: (f = msg.getDeliveryAddress()) && entity_common_pb.Address.toObject(includeInstance, f),
    deliveryTimeRaw: jspb.Message.getFieldWithDefault(msg, 20, ""),
    deliveryTime: jspb.Message.getFieldWithDefault(msg, 21, 0),
    postman: (f = msg.getPostman()) && entity_common_pb.Postman.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Delivery}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.Delivery;
  return proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Delivery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Delivery}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeliveryAddressRaw(value);
      break;
    case 11:
      var value = new entity_common_pb.Address;
      reader.readMessage(value,entity_common_pb.Address.deserializeBinaryFromReader);
      msg.setDeliveryAddress(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeliveryTimeRaw(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDeliveryTime(value);
      break;
    case 30:
      var value = new entity_common_pb.Postman;
      reader.readMessage(value,entity_common_pb.Postman.deserializeBinaryFromReader);
      msg.setPostman(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Delivery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeliveryAddressRaw();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getDeliveryAddress();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      entity_common_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getDeliveryTimeRaw();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getDeliveryTime();
  if (f !== 0) {
    writer.writeInt64(
      21,
      f
    );
  }
  f = message.getPostman();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      entity_common_pb.Postman.serializeBinaryToWriter
    );
  }
};


/**
 * optional string delivery_address_raw = 10;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.getDeliveryAddressRaw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.setDeliveryAddressRaw = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional Address delivery_address = 11;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Address}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.getDeliveryAddress = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Address} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Address, 11));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Address|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.setDeliveryAddress = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.clearDeliveryAddress = function() {
  this.setDeliveryAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.hasDeliveryAddress = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string delivery_time_raw = 20;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.getDeliveryTimeRaw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.setDeliveryTimeRaw = function(value) {
  jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional int64 delivery_time = 21;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.getDeliveryTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.setDeliveryTime = function(value) {
  jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional Postman postman = 30;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Postman}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.getPostman = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Postman} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Postman, 30));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Postman|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.setPostman = function(value) {
  jspb.Message.setWrapperField(this, 30, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.clearPostman = function() {
  this.setPostman(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Delivery.prototype.hasPostman = function() {
  return jspb.Message.getField(this, 30) != null;
};


goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.entity);
