/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fullPath: jspb.Message.getFieldWithDefault(msg, 2, ""),
    signedUploadUrl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    signedDownloadUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mediaType: jspb.Message.getFieldWithDefault(msg, 5, ""),
    bytes: msg.getBytes_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject;
  return proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullPath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignedUploadUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignedDownloadUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMediaType(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFullPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSignedUploadUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSignedDownloadUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMediaType();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBytes_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string full_path = 2;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getFullPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setFullPath = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string signed_upload_url = 3;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getSignedUploadUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setSignedUploadUrl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string signed_download_url = 4;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getSignedDownloadUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setSignedDownloadUrl = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string media_type = 5;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getMediaType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setMediaType = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bytes bytes = 6;
 * @return {!(string|Uint8Array)}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getBytes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes bytes = 6;
 * This is a type-conversion wrapper around `getBytes()`
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytes()));
};


/**
 * optional bytes bytes = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytes()`
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.getBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytes()));
};


/** @param {!(string|Uint8Array)} value */
proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject.prototype.setBytes = function(value) {
  jspb.Message.setProto3BytesField(this, 6, value);
};


goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.entity);
