/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entity_common_pb = require('../entity/common_pb.js');
var entity_customer_pb = require('../entity/customer_pb.js');
var entity_delivery_pb = require('../entity/delivery_pb.js');
var entity_product_pb = require('../entity/product_pb.js');
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.Order', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jiaonidaigou.appengine.wiremodel.entity.Order.repeatedFields_, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.Order, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.Order.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.Order';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.repeatedFields_ = [20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.Order.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Order} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orderGroupTag: jspb.Message.getFieldWithDefault(msg, 5, ""),
    customer: (f = msg.getCustomer()) && entity_customer_pb.Customer.toObject(includeInstance, f),
    entiresList: jspb.Message.toObjectList(msg.getEntiresList(),
    proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.toObject, includeInstance),
    creationTime: jspb.Message.getFieldWithDefault(msg, 30, 0),
    delivery: (f = msg.getDelivery()) && entity_delivery_pb.Delivery.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Order}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.Order;
  return proto.jiaonidaigou.appengine.wiremodel.entity.Order.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Order} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Order}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderGroupTag(value);
      break;
    case 10:
      var value = new entity_customer_pb.Customer;
      reader.readMessage(value,entity_customer_pb.Customer.deserializeBinaryFromReader);
      msg.setCustomer(value);
      break;
    case 20:
      var value = new proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry;
      reader.readMessage(value,proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.deserializeBinaryFromReader);
      msg.addEntires(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreationTime(value);
      break;
    case 40:
      var value = new entity_delivery_pb.Delivery;
      reader.readMessage(value,entity_delivery_pb.Delivery.deserializeBinaryFromReader);
      msg.setDelivery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.Order.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Order} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderGroupTag();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCustomer();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      entity_customer_pb.Customer.serializeBinaryToWriter
    );
  }
  f = message.getEntiresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.serializeBinaryToWriter
    );
  }
  f = message.getCreationTime();
  if (f !== 0) {
    writer.writeInt64(
      30,
      f
    );
  }
  f = message.getDelivery();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      entity_delivery_pb.Delivery.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string order_group_tag = 5;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getOrderGroupTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setOrderGroupTag = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Customer customer = 10;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getCustomer = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Customer} */ (
    jspb.Message.getWrapperField(this, entity_customer_pb.Customer, 10));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setCustomer = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.clearCustomer = function() {
  this.setCustomer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.hasCustomer = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated OrderEntry entires = 20;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getEntiresList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry, 20));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setEntiresList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.addEntires = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.clearEntiresList = function() {
  this.setEntiresList([]);
};


/**
 * optional int64 creation_time = 30;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getCreationTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setCreationTime = function(value) {
  jspb.Message.setProto3IntField(this, 30, value);
};


/**
 * optional Delivery delivery = 40;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Delivery}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.getDelivery = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Delivery} */ (
    jspb.Message.getWrapperField(this, entity_delivery_pb.Delivery, 40));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Delivery|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.setDelivery = function(value) {
  jspb.Message.setWrapperField(this, 40, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.clearDelivery = function() {
  this.setDelivery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Order.prototype.hasDelivery = function() {
  return jspb.Message.getField(this, 40) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && entity_product_pb.Product.toObject(includeInstance, f),
    unitSellingPrice: (f = msg.getUnitSellingPrice()) && entity_common_pb.Price.toObject(includeInstance, f),
    quantity: jspb.Message.getFieldWithDefault(msg, 30, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry;
  return proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10:
      var value = new entity_product_pb.Product;
      reader.readMessage(value,entity_product_pb.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 20:
      var value = new entity_common_pb.Price;
      reader.readMessage(value,entity_common_pb.Price.deserializeBinaryFromReader);
      msg.setUnitSellingPrice(value);
      break;
    case 30:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      entity_product_pb.Product.serializeBinaryToWriter
    );
  }
  f = message.getUnitSellingPrice();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      entity_common_pb.Price.serializeBinaryToWriter
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      30,
      f
    );
  }
};


/**
 * optional Product product = 10;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Product}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.getProduct = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Product} */ (
    jspb.Message.getWrapperField(this, entity_product_pb.Product, 10));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Product|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.setProduct = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Price unit_selling_price = 20;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Price}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.getUnitSellingPrice = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Price} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Price, 20));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Price|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.setUnitSellingPrice = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.clearUnitSellingPrice = function() {
  this.setUnitSellingPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.hasUnitSellingPrice = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional int32 quantity = 30;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderEntry.prototype.setQuantity = function(value) {
  jspb.Message.setProto3IntField(this, 30, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.repeatedFields_, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.repeatedFields_ = [20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 10, ""),
    ordersList: jspb.Message.toObjectList(msg.getOrdersList(),
    proto.jiaonidaigou.appengine.wiremodel.entity.Order.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup;
  return proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 20:
      var value = new proto.jiaonidaigou.appengine.wiremodel.entity.Order;
      reader.readMessage(value,proto.jiaonidaigou.appengine.wiremodel.entity.Order.deserializeBinaryFromReader);
      msg.addOrders(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getOrdersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.jiaonidaigou.appengine.wiremodel.entity.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tag = 10;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.setTag = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated Order orders = 20;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.Order>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.getOrdersList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.Order>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jiaonidaigou.appengine.wiremodel.entity.Order, 20));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.Order>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.setOrdersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Order=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Order}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.addOrders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.Order, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.OrderGroup.prototype.clearOrdersList = function() {
  this.setOrdersList([]);
};


goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.entity);
