/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entity_common_pb = require('../entity/common_pb.js');
var entity_media_object_pb = require('../entity/media_object_pb.js');
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.Product', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jiaonidaigou.appengine.wiremodel.entity.Product.repeatedFields_, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.Product, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.Product.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.Product';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.repeatedFields_ = [21,40];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.Product.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Product} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    category: jspb.Message.getFieldWithDefault(msg, 2, 0),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    mainMedia: (f = msg.getMainMedia()) && entity_media_object_pb.MediaObject.toObject(includeInstance, f),
    otherMediaList: jspb.Message.toObjectList(msg.getOtherMediaList(),
    entity_media_object_pb.MediaObject.toObject, includeInstance),
    suggestedUnitPrice: (f = msg.getSuggestedUnitPrice()) && entity_common_pb.Price.toObject(includeInstance, f),
    tagsList: jspb.Message.getRepeatedField(msg, 40)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Product}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.Product;
  return proto.jiaonidaigou.appengine.wiremodel.entity.Product.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Product} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.Product}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 20:
      var value = new entity_media_object_pb.MediaObject;
      reader.readMessage(value,entity_media_object_pb.MediaObject.deserializeBinaryFromReader);
      msg.setMainMedia(value);
      break;
    case 21:
      var value = new entity_media_object_pb.MediaObject;
      reader.readMessage(value,entity_media_object_pb.MediaObject.deserializeBinaryFromReader);
      msg.addOtherMedia(value);
      break;
    case 30:
      var value = new entity_common_pb.Price;
      reader.readMessage(value,entity_common_pb.Price.deserializeBinaryFromReader);
      msg.setSuggestedUnitPrice(value);
      break;
    case 40:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.Product.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.Product} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCategory();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMainMedia();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      entity_media_object_pb.MediaObject.serializeBinaryToWriter
    );
  }
  f = message.getOtherMediaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      entity_media_object_pb.MediaObject.serializeBinaryToWriter
    );
  }
  f = message.getSuggestedUnitPrice();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      entity_common_pb.Price.serializeBinaryToWriter
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      40,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ProductCategory category = 2;
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getCategory = function() {
  return /** @type {!proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setCategory = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string brand = 4;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setBrand = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional MediaObject main_media = 20;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getMainMedia = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject} */ (
    jspb.Message.getWrapperField(this, entity_media_object_pb.MediaObject, 20));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setMainMedia = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.clearMainMedia = function() {
  this.setMainMedia(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.hasMainMedia = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * repeated MediaObject other_media = 21;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getOtherMediaList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject>} */ (
    jspb.Message.getRepeatedWrapperField(this, entity_media_object_pb.MediaObject, 21));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setOtherMediaList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.addOtherMedia = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.MediaObject, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.clearOtherMediaList = function() {
  this.setOtherMediaList([]);
};


/**
 * optional Price suggested_unit_price = 30;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Price}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getSuggestedUnitPrice = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Price} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Price, 30));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Price|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setSuggestedUnitPrice = function(value) {
  jspb.Message.setWrapperField(this, 30, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.clearSuggestedUnitPrice = function() {
  this.setSuggestedUnitPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.hasSuggestedUnitPrice = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * repeated string tags = 40;
 * @return {!Array.<string>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.getTagsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 40));
};


/** @param {!Array.<string>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.setTagsList = function(value) {
  jspb.Message.setField(this, 40, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.addTags = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 40, value, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.Product.prototype.clearTagsList = function() {
  this.setTagsList([]);
};


/**
 * @enum {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ProductCategory = {
  UNKNOWN: 0,
  ACCESSORIES: 1,
  BABY_PRODUCTS: 2,
  BAGS: 3,
  CLOTHES: 4,
  DAILY_NECESSITIES: 5,
  FOOD: 6,
  HEALTH_SUPPLEMENTS: 7,
  LARGE_COMMERCIAL_GOODS: 8,
  LARGE_ITEMS: 9,
  MAKE_UP: 10,
  MILK_POWDER: 11,
  SHOES: 12,
  SMALL_APPLIANCES: 13,
  TOYS: 14,
  WATCHES: 15
};

goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.entity);
