/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entity_common_pb = require('../entity/common_pb.js');
var entity_customer_pb = require('../entity/customer_pb.js');
var entity_product_pb = require('../entity/product_pb.js');
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.repeatedFields_, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.repeatedFields_ = [5,40];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    receiver: (f = msg.getReceiver()) && entity_customer_pb.Customer.toObject(includeInstance, f),
    creationTime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    productEntriesList: jspb.Message.toObjectList(msg.getProductEntriesList(),
    proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.toObject, includeInstance),
    productSummary: jspb.Message.getFieldWithDefault(msg, 6, ""),
    totalWeightLb: +jspb.Message.getFieldWithDefault(msg, 7, 0.0),
    postman: (f = msg.getPostman()) && entity_common_pb.Postman.toObject(includeInstance, f),
    trackingNumber: jspb.Message.getFieldWithDefault(msg, 32, ""),
    shippingHistoryList: jspb.Message.toObjectList(msg.getShippingHistoryList(),
    proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.toObject, includeInstance),
    teddyOrderId: jspb.Message.getFieldWithDefault(msg, 100, ""),
    teddyFormattedId: jspb.Message.getFieldWithDefault(msg, 101, ""),
    senderName: jspb.Message.getFieldWithDefault(msg, 110, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder;
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = new entity_customer_pb.Customer;
      reader.readMessage(value,entity_customer_pb.Customer.deserializeBinaryFromReader);
      msg.setReceiver(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreationTime(value);
      break;
    case 5:
      var value = new proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry;
      reader.readMessage(value,proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.deserializeBinaryFromReader);
      msg.addProductEntries(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductSummary(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalWeightLb(value);
      break;
    case 30:
      var value = new entity_common_pb.Postman;
      reader.readMessage(value,entity_common_pb.Postman.deserializeBinaryFromReader);
      msg.setPostman(value);
      break;
    case 32:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackingNumber(value);
      break;
    case 40:
      var value = new proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry;
      reader.readMessage(value,proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.deserializeBinaryFromReader);
      msg.addShippingHistory(value);
      break;
    case 100:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeddyOrderId(value);
      break;
    case 101:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeddyFormattedId(value);
      break;
    case 110:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getReceiver();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      entity_customer_pb.Customer.serializeBinaryToWriter
    );
  }
  f = message.getCreationTime();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getProductEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.serializeBinaryToWriter
    );
  }
  f = message.getProductSummary();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTotalWeightLb();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getPostman();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      entity_common_pb.Postman.serializeBinaryToWriter
    );
  }
  f = message.getTrackingNumber();
  if (f.length > 0) {
    writer.writeString(
      32,
      f
    );
  }
  f = message.getShippingHistoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      40,
      f,
      proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.serializeBinaryToWriter
    );
  }
  f = message.getTeddyOrderId();
  if (f.length > 0) {
    writer.writeString(
      100,
      f
    );
  }
  f = message.getTeddyFormattedId();
  if (f.length > 0) {
    writer.writeString(
      101,
      f
    );
  }
  f = message.getSenderName();
  if (f.length > 0) {
    writer.writeString(
      110,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status = {
  CREATED: 0,
  PENDING: 1,
  CN_TRACKING_NUMBER_ASSIGNED: 2,
  CN_POSTMAN_ASSIGNED: 3,
  DELIVERED: 4
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && entity_product_pb.Product.toObject(includeInstance, f),
    quantity: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sellPrice: (f = msg.getSellPrice()) && entity_common_pb.Price.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry;
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new entity_product_pb.Product;
      reader.readMessage(value,entity_product_pb.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    case 3:
      var value = new entity_common_pb.Price;
      reader.readMessage(value,entity_common_pb.Price.deserializeBinaryFromReader);
      msg.setSellPrice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      entity_product_pb.Product.serializeBinaryToWriter
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSellPrice();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      entity_common_pb.Price.serializeBinaryToWriter
    );
  }
};


/**
 * optional Product product = 1;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Product}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.getProduct = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Product} */ (
    jspb.Message.getWrapperField(this, entity_product_pb.Product, 1));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Product|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.setProduct = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 quantity = 2;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.setQuantity = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Price sell_price = 3;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Price}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.getSellPrice = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Price} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Price, 3));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Price|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.setSellPrice = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.clearSellPrice = function() {
  this.setSellPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry.prototype.hasSellPrice = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.displayName = 'proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    status: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry;
  return proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 timestamp = 1;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Status status = 2;
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getStatus = function() {
  return /** @type {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.Status} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setStatus = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Customer receiver = 3;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getReceiver = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Customer} */ (
    jspb.Message.getWrapperField(this, entity_customer_pb.Customer, 3));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setReceiver = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.clearReceiver = function() {
  this.setReceiver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.hasReceiver = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 creation_time = 4;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getCreationTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setCreationTime = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated ProductEntry product_entries = 5;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getProductEntriesList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry, 5));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setProductEntriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.addProductEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.clearProductEntriesList = function() {
  this.setProductEntriesList([]);
};


/**
 * optional string product_summary = 6;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getProductSummary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setProductSummary = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional double total_weight_lb = 7;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getTotalWeightLb = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 7, 0.0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setTotalWeightLb = function(value) {
  jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional Postman postman = 30;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Postman}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getPostman = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Postman} */ (
    jspb.Message.getWrapperField(this, entity_common_pb.Postman, 30));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Postman|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setPostman = function(value) {
  jspb.Message.setWrapperField(this, 30, value);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.clearPostman = function() {
  this.setPostman(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.hasPostman = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional string tracking_number = 32;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getTrackingNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 32, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setTrackingNumber = function(value) {
  jspb.Message.setProto3StringField(this, 32, value);
};


/**
 * repeated ShippingHistoryEntry shipping_history = 40;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry>}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getShippingHistoryList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry, 40));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry>} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setShippingHistoryList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 40, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.addShippingHistory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 40, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ShippingHistoryEntry, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.clearShippingHistoryList = function() {
  this.setShippingHistoryList([]);
};


/**
 * optional string teddy_order_id = 100;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getTeddyOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 100, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setTeddyOrderId = function(value) {
  jspb.Message.setProto3StringField(this, 100, value);
};


/**
 * optional string teddy_formatted_id = 101;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getTeddyFormattedId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 101, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setTeddyFormattedId = function(value) {
  jspb.Message.setProto3StringField(this, 101, value);
};


/**
 * optional string sender_name = 110;
 * @return {string}
 */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.getSenderName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 110, ""));
};


/** @param {string} value */
proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.prototype.setSenderName = function(value) {
  jspb.Message.setProto3StringField(this, 110, value);
};


goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.entity);
