/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var entity_customer_pb = require('../entity/customer_pb.js');
var entity_shipping_oder_pb = require('../entity/shipping_oder_pb.js');
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest', null, global);
goog.exportSymbol('proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.repeatedFields_, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.displayName = 'proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    receiver: (f = msg.getReceiver()) && entity_customer_pb.Customer.toObject(includeInstance, f),
    productEntriesList: jspb.Message.toObjectList(msg.getProductEntriesList(),
    entity_shipping_oder_pb.ShippingOrder.ProductEntry.toObject, includeInstance),
    totalWeightLb: +jspb.Message.getFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest;
  return proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new entity_customer_pb.Customer;
      reader.readMessage(value,entity_customer_pb.Customer.deserializeBinaryFromReader);
      msg.setReceiver(value);
      break;
    case 2:
      var value = new entity_shipping_oder_pb.ShippingOrder.ProductEntry;
      reader.readMessage(value,entity_shipping_oder_pb.ShippingOrder.ProductEntry.deserializeBinaryFromReader);
      msg.addProductEntries(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalWeightLb(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReceiver();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      entity_customer_pb.Customer.serializeBinaryToWriter
    );
  }
  f = message.getProductEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      entity_shipping_oder_pb.ShippingOrder.ProductEntry.serializeBinaryToWriter
    );
  }
  f = message.getTotalWeightLb();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional jiaonidaigou.appengine.wiremodel.entity.Customer receiver = 1;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.getReceiver = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.Customer} */ (
    jspb.Message.getWrapperField(this, entity_customer_pb.Customer, 1));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.Customer|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.setReceiver = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.clearReceiver = function() {
  this.setReceiver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.hasReceiver = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry product_entries = 2;
 * @return {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.getProductEntriesList = function() {
  return /** @type{!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, entity_shipping_oder_pb.ShippingOrder.ProductEntry, 2));
};


/** @param {!Array.<!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry>} value */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.setProductEntriesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.addProductEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder.ProductEntry, opt_index);
};


proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.clearProductEntriesList = function() {
  this.setProductEntriesList([]);
};


/**
 * optional double total_weight_lb = 3;
 * @return {number}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.getTotalWeightLb = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderRequest.prototype.setTotalWeightLb = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.displayName = 'proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    shippingOrder: (f = msg.getShippingOrder()) && entity_shipping_oder_pb.ShippingOrder.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse;
  return proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new entity_shipping_oder_pb.ShippingOrder;
      reader.readMessage(value,entity_shipping_oder_pb.ShippingOrder.deserializeBinaryFromReader);
      msg.setShippingOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShippingOrder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      entity_shipping_oder_pb.ShippingOrder.serializeBinaryToWriter
    );
  }
};


/**
 * optional jiaonidaigou.appengine.wiremodel.entity.ShippingOrder shipping_order = 1;
 * @return {?proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.getShippingOrder = function() {
  return /** @type{?proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder} */ (
    jspb.Message.getWrapperField(this, entity_shipping_oder_pb.ShippingOrder, 1));
};


/** @param {?proto.jiaonidaigou.appengine.wiremodel.entity.ShippingOrder|undefined} value */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.setShippingOrder = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.clearShippingOrder = function() {
  this.setShippingOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jiaonidaigou.appengine.wiremodel.api.CreateShippingOrderResponse.prototype.hasShippingOrder = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.jiaonidaigou.appengine.wiremodel.api);
